### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Kinneyzhang** [lepisma/pile#38]
Could you give a specific README? It will be handy to use for newbies.

**Comment by lepisma** [comment]
Hi,

I am not sure if I can promise this any moment soon. The code here might be generalizable but I have made no extra effort to do that and wrote most of the things to work with rest of my config.

Though I am not sure if it's not possible. I think a couple of changes might fix it :thinking: 

But yeah, I think starting from org-publish in general might be a better place since I am just wrapping around that.
